import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { Navbar } from './components/Navbar';
import { RegisterModal } from './components/Modals/Register';
import ToasterProvider from './providers/ToastProvider';
import { User } from './interfaces/user';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Trip Tempo',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	//const currentUser= undefined
	const currentUser: User = {
		id: '1',
		name: 'Bryan Aguilar',
		email: 'baguilar@test.com',
		emailVerified: true,
		image: ''
	};

	return (
		<html lang="en">
			<body className={font.className}>
				<ToasterProvider />
				<RegisterModal />
				<Navbar currentUser={currentUser} />
				{children}
			</body>
		</html>
	);
}
