import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { Nabvar } from './components/Navbar';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Trip Tempo',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={font.className}>
				<Nabvar />
				{children}
			</body>
		</html>
	);
}
