import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { Navbar } from './components/Navbar';
import { RegisterModal } from './components/Modals/Register';
import { LoginModal } from './components/Modals/Login';
import { RentModal } from './components/Modals/Rent';
import { getCurrentUser } from './data/mock';
import { SearchModal } from './components/Modals/Search';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Trip Tempo',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const currentUser = getCurrentUser();

	return (
		<html lang="en">
			<body className={font.className}>
				{/* Modals */}
				<RegisterModal />
				<LoginModal />
				<RentModal />
				<SearchModal />
				<Navbar currentUser={currentUser} />
				<div className="pb-20 pt-28">{children}</div>
			</body>
		</html>
	);
}
