import './globals.css';
import type { Metadata } from 'next';
import { RegisterModal } from '../components/Modals/Register';
import { LoginModal } from '../components/Modals/Login';
import { Navbar } from '../components/Navbar';

export const metadata: Metadata = {
	title: 'Trip Tempo',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html lang="en">
			<body className="w-full">
				{/* Modals */}
				<RegisterModal />
				<LoginModal />
				{/* Navbar */}
				<Navbar />
				<div className="py-32">{children}</div>
			</body>
		</html>
	);
}
