import './globals.css';
import type { Metadata } from 'next';

import { Navbar } from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/themeProvider';

export const metadata: Metadata = {
	title: 'Trip Tempo',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html lang="en">
			<body className="w-full">
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<Navbar />
					<main className="py-32">{children}</main>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
